apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: remix-app
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: remix-app
    version: 1.0.0
  name: remix-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: remix-app
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: remix-app
        app: remix-app
        version: 1.0.0
    spec:
      containers:
        - image: 554509907436.dkr.ecr.us-east-1.amazonaws.com/remix-app:v0.0.2-remix-app
          imagePullPolicy: Always
          name: {{ .Values.name }}
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP

